### PR TITLE
readd gnome 3.18 support

### PR DESCRIPTION
**Pull request by noerw**
there were no breaking changes, so its safe to keep supporting it

### CODE REVIEW

**Comment by noerw** [comment]
@awamper *ping*

**Comment by Hanzei** [comment]
Fixed with 661292b6974370e3784957adc163fadf0e84b5e1

**Comment by Hanzei** [comment]
Can we close this?

**Comment by noerw** [comment]
oh, so you keep old versions on separate branches! didnt knew that.
yes, we can close this PR then.

Then it would be good however to
1. mention this in the readme for manual installation
2. keep a branch for the latest supported version, which is in sync with master, until next generation is released. This would allow me to install from branch `3.X` without the chance of a breaking change for my gnome version..

**Comment by Hanzei** [comment]
@noerw #24 is merged

**Pull request closed without merging**
